import { createGlobalStyle, css } from 'styled-components';

const GlobalStyle = createGlobalStyle`
@import url("https://fonts.googleapis.com/css2?family=Montserrat:wght@300;600&display=swap");

*, *::before,*, *::after {
   box-sizing: border-box;
   * {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
}
html {
   font-size:62.5%;
}
body {
   font-size:1rem;
   font-family: Montserrat, sans-serif;
   background-color:  #DBE3E9;
   margin: 0;
   
   ${({ dark }) =>
    dark &&
     css`
       background-color: black;
       color:white;
     `}  
}
@keyframes appear {
  0% {
    opacity: 0;
    top: 35px;
  }
  100% {
    opacity: 1;
    top: 0;
  }
}
/* ----------------------------------------------
 * Generated by Animista on 2023-1-2 9:0:59
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-vert-center
 * ----------------------------------------
 */
@-webkit-keyframes rotate-vert-center {
  0% {
    -webkit-transform: rotateY(0);
            transform: rotateY(0);
  }
  100% {
    -webkit-transform: rotateY(360deg);
            transform: rotateY(360deg);
  }
}
@keyframes rotate-vert-center {
  0% {
    -webkit-transform: rotateY(0);
            transform: rotateY(0);
  }
  100% {
    -webkit-transform: rotateY(360deg);
            transform: rotateY(360deg);
  }
}

`;

export default GlobalStyle;
